### ISSUE TITLE
About bug fixing of CLI command dns recordset list.

### ISSUE THREAD

**Issue by shimisho** [nttcom/eclsdk#44]
Although it is mentioned in the following pull request, when the record records list exceeds 100, only the first 100 items are displayed when the list records command is used.

https://github.com/nttcom/eclcli/pull/62

In order to solve this problem, we want to receive a limit (pagination size) parameter from the CLI command.

**Comment by kazyshr** [comment]
This issue has been fixed by the following pull request. You can use pagination using limit and marker arguments.
https://github.com/nttcom/eclsdk/pull/45
